# github action to setup node environment, install dependencies, and run the GYSR core test suite with Hardhat
name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "npm"

      - name: Install system depdencies
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev libudev-dev

      - name: Install npm dependencies
        run: npm ci

      - name: Compile solidity contracts
        run: npx hardhat compile

      - name: Run hardhat tests
        run: npx hardhat test
